import { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, CheckCircle2, CircleDollarSign, Copy, Gift, Plus, Send, TicketPercent, TrendingUp, UsersRound } from "lucide-react";
import { Badge, Button, Drawer, Modal } from "../../../components/ui";
import { useMarketing } from "../MarketingContext";
import type { Campaign, CampaignStatus, Coupon, Tone } from "../types";
import { ConfirmDialog, MarketingKpi, MiniStat, SectionCard } from "../components/MarketingShared";

const campaignTone:Record<CampaignStatus,Tone>={"草稿":"neutral","待主管审批":"amber","待财务审批":"amber","进行中":"green","已结束":"blue","已下线":"red"};
const activityTrend=[{date:"09-01",join:420,revenue:82},{date:"09-04",join:680,revenue:126},{date:"09-07",join:920,revenue:184},{date:"09-10",join:1280,revenue:246},{date:"09-13",join:1680,revenue:318},{date:"09-15",join:2040,revenue:386}];

export function CampaignsSection(){
  const {campaigns,addCampaign,updateCampaignStatus,notify}=useMarketing();
  const [query,setQuery]=useState("");
  const [status,setStatus]=useState("全部");
  const [createOpen,setCreateOpen]=useState(false);
  const [selected,setSelected]=useState<Campaign|null>(null);
  const [review,setReview]=useState<Campaign|null>(null);
  const [confirm,setConfirm]=useState<Campaign|null>(null);
  const [form,setForm]=useState({name:"",type:"节点营销",period:"2026-09-20 至 2026-10-20",course:"税务师冲刺班",audience:"税务师报考用户",budget:"100000",discount:"满 5000 减 600",stock:"3000",threshold:"5000"});
  const rows=useMemo(()=>campaigns.filter(item=>(status==="全部"||item.status===status)&&`${item.name}${item.type}${item.course}`.includes(query)),[campaigns,query,status]);
  const submit=()=>{if(!form.name.trim())return notify("请填写活动名称");addCampaign({id:`CAM-${Date.now().toString().slice(-6)}`,name:form.name,type:form.type,period:form.period,audience:form.audience,course:form.course,budget:Number(form.budget),participants:0,revenue:0,roi:0,status:"草稿",approval:"未提交"});setCreateOpen(false);};
  return <div className="marketing-section">
    <div className="marketing-toolbar"><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索活动名称、类型或课程"/><select className="select" value={status} onChange={e=>setStatus(e.target.value)}>{["全部","草稿","待主管审批","待财务审批","进行中","已结束","已下线"].map(item=><option key={item}>{item}</option>)}</select><span className="spacer"/><Button variant="secondary" onClick={()=>notify("已打开营销活动模板库")}>活动模板</Button><Button onClick={()=>setCreateOpen(true)}><Plus size={14}/>创建活动</Button></div>
    <div className="marketing-kpi-grid">
      <MarketingKpi label="进行中活动" value={`${campaigns.filter(item=>item.status==="进行中").length} 个`} detail="2 个健康度优秀" icon={TrendingUp}/>
      <MarketingKpi label="待审批" value={`${campaigns.filter(item=>item.status.includes("审批")).length} 个`} detail="财务待办 1 个" icon={CheckCircle2} tone="amber"/>
      <MarketingKpi label="活动总收入" value="¥ 306.2 万" detail="本月已归因" icon={CircleDollarSign} tone="green"/>
      <MarketingKpi label="累计参与" value="9,003" detail="去重用户 7,628" icon={UsersRound}/>
    </div>
    <SectionCard title="活动列表" detail={`共 ${rows.length} 个活动 · 审批、上线与监控状态实时同步`}>
      <div className="marketing-table-scroll"><table className="data-table marketing-table campaign-table"><thead><tr><th>活动</th><th>类型 / 周期</th><th>课程 / 人群</th><th>预算</th><th>参与</th><th>收入</th><th>ROI</th><th>状态</th><th>审批</th><th>操作</th></tr></thead><tbody>{rows.map(item=><tr key={item.id}><td><strong>{item.name}</strong><small>{item.id}</small></td><td>{item.type}<small>{item.period}</small></td><td>{item.course}<small>{item.audience}</small></td><td>¥{item.budget.toLocaleString()}</td><td>{item.participants.toLocaleString()}</td><td>¥{item.revenue.toLocaleString()}</td><td><b className={item.roi>=4?"text-green":"text-amber"}>{item.roi||"-"}</b></td><td><Badge tone={campaignTone[item.status]}>{item.status}</Badge></td><td>{item.approval}</td><td><div className="row-actions"><button onClick={()=>setSelected(item)}>监控</button>{item.status==="草稿"&&<button onClick={()=>updateCampaignStatus(item.id,"待主管审批")}>提交</button>}{item.status==="待主管审批"&&<button onClick={()=>updateCampaignStatus(item.id,"待财务审批")}>主管通过</button>}{item.status==="待财务审批"&&<button onClick={()=>updateCampaignStatus(item.id,"进行中")}>财务通过</button>}{item.status==="进行中"&&<button className="danger-link" onClick={()=>setConfirm(item)}>下线</button>}{item.status==="已结束"&&<button onClick={()=>setReview(item)}>复盘</button>}<button onClick={()=>{setForm({...form,name:`${item.name}（复用）`,type:item.type,period:item.period,course:item.course,audience:item.audience,budget:String(item.budget)});setCreateOpen(true)}}><Copy size={12}/>复用</button></div></td></tr>)}</tbody></table></div>
    </SectionCard>
    <Modal open={createOpen} onClose={()=>setCreateOpen(false)} title="创建营销活动"><div className="form-grid">{([["活动名称","name"],["活动类型","type"],["活动周期","period"],["适用课程","course"],["目标人群","audience"],["目标预算","budget"],["优惠规则","discount"],["活动库存","stock"],["使用门槛","threshold"]] as const).map(([label,key])=><label className={`field ${key==="name"?"form-span-2":""}`} key={key}><span>{label}</span><input className="input" type={key==="budget"||key==="stock"||key==="threshold"?"number":"text"} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><div className="marketing-rule-checks"><label><input type="checkbox" defaultChecked/>允许与会员折扣叠加</label><label><input type="checkbox"/>限制每人参与 1 次</label><label><input type="checkbox" defaultChecked/>库存不足自动预警</label></div><div className="form-actions"><Button variant="secondary" onClick={()=>setCreateOpen(false)}>取消</Button><Button onClick={submit}>保存草稿</Button></div></Modal>
    <Drawer open={Boolean(selected)} onClose={()=>setSelected(null)} title={`${selected?.name??""} · 实时监控`} wide>{selected&&<><div className="marketing-stat-strip"><MiniStat label="参与人数" value={selected.participants.toLocaleString()}/><MiniStat label="领取权益" value={Math.round(selected.participants*.82).toLocaleString()}/><MiniStat label="实际使用" value={Math.round(selected.participants*.54).toLocaleString()}/><MiniStat label="转化金额" value={`¥${selected.revenue.toLocaleString()}`}/><MiniStat label="实时 ROI" value={String(selected.roi)}/></div><div className="marketing-drawer-chart"><ResponsiveContainer><LineChart data={activityTrend}><CartesianGrid vertical={false} stroke="rgb(var(--line))"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Line dataKey="join" name="参与" stroke="#2563eb" strokeWidth={2}/><Line dataKey="revenue" name="收入(万)" stroke="#10b981" strokeWidth={2}/></LineChart></ResponsiveContainer></div><div className="marketing-warning"><AlertTriangle size={16}/><span>小红书渠道转化率低于活动平均 18%，建议调整素材版本。</span><Button variant="secondary" onClick={()=>notify("已创建渠道素材优化任务")}>创建优化任务</Button></div></>}</Drawer>
    <Modal open={Boolean(review)} onClose={()=>setReview(null)} title="结束活动复盘">{review&&<><div className="marketing-stat-strip"><MiniStat label="目标达成" value="112%"/><MiniStat label="投入产出" value={String(review.roi)}/><MiniStat label="新增学员" value="1,042"/><MiniStat label="复购贡献" value="18.6%"/></div><div className="review-profile"><strong>核心用户画像</strong><p>26-35 岁在职财务人群占 58%，首次考证用户占 42%，公众号与图书渠道贡献最高。</p><strong>经验总结</strong><textarea defaultValue="考前 30 天分层触达效果最佳；组合套餐应提前准备库存和退券规则。"/></div><div className="form-actions"><Button onClick={()=>{notify("活动复盘已归档");setReview(null)}}>保存复盘</Button></div></>}</Modal>
    <ConfirmDialog open={Boolean(confirm)} title="确认下线活动" detail={`下线「${confirm?.name}」后，所有投放链接和优惠权益将停止生效。`} confirmLabel="确认下线" danger onClose={()=>setConfirm(null)} onConfirm={()=>confirm&&updateCampaignStatus(confirm.id,"已下线")}/>
  </div>;
}

const promoRules=[["阶梯满减","满 5,000 减 300；满 10,000 减 900","运行中"],["第二件半价","同品类第二门课程 5 折","待启用"],["组合套餐","图书 + 课程组合价 3,980 元","运行中"],["多科联报","每增加一科再减 300 元","运行中"],["老学员折扣","历史付费学员续报 85 折","运行中"]];

export function CouponsSection(){
  const {coupons,addCoupon,issueCoupon,notify}=useMarketing();
  const [createOpen,setCreateOpen]=useState(false);
  const [target,setTarget]=useState<Coupon|null>(null);
  const [name,setName]=useState("CPA 全科联报限时立减");
  const [type,setType]=useState("满减券");
  const [value,setValue]=useState("满 12,800 减 2,000");
  const [audience,setAudience]=useState("CPA 高意向未报名人群");
  const [amount,setAmount]=useState(1200);
  const [enabled,setEnabled]=useState(()=>new Set([0,2,3,4]));
  return <div className="marketing-section">
    <div className="marketing-toolbar"><div className="segmented">{["优惠券","促销规则","发放记录","价格保护"].map((item,index)=><button className={index===0?"active":""} onClick={()=>notify(`已切换至${item}视图`)} key={item}>{item}</button>)}</div><span className="spacer"/><Button variant="secondary" onClick={()=>notify("已生成 200 个唯一兑换码并导出")}>生成兑换码</Button><Button onClick={()=>setCreateOpen(true)}><Plus size={14}/>创建优惠券</Button></div>
    <div className="marketing-kpi-grid"><MarketingKpi label="有效优惠券" value="18 种" detail="覆盖七类券型" icon={TicketPercent}/><MarketingKpi label="累计核销" value="4,596" detail="核销率 36.9%" icon={CheckCircle2} tone="green"/><MarketingKpi label="券带动收入" value="¥ 228.4 万" detail="整体 ROI 5.2" icon={CircleDollarSign}/><MarketingKpi label="退款退券" value="128 笔" detail="环比 +3.2%" icon={AlertTriangle} tone="amber"/></div>
    <div className="marketing-dashboard-grid">
      <SectionCard title="优惠券资产" detail="满减、折扣、代金、兑换、运费、礼品与课程券" className="wide"><div className="marketing-table-scroll"><table className="data-table marketing-table"><thead><tr><th>优惠券</th><th>券型</th><th>优惠内容</th><th>发放 / 使用</th><th>带动收入</th><th>ROI</th><th>状态</th><th>操作</th></tr></thead><tbody>{coupons.map(item=><tr key={item.id}><td><strong>{item.name}</strong><small>{item.id}</small></td><td>{item.type}</td><td>{item.value}</td><td>{item.issued.toLocaleString()} / {item.used.toLocaleString()}</td><td>¥{item.revenue.toLocaleString()}</td><td>{item.roi||"-"}</td><td><Badge tone={item.status==="发放中"?"green":item.status==="待发放"?"amber":"neutral"}>{item.status}</Badge></td><td><button className="link" onClick={()=>setTarget(item)}>分群发放</button></td></tr>)}</tbody></table></div></SectionCard>
      <SectionCard title="促销规则" detail="可组合叠加并受价格保护约束"><div className="marketing-rule-list">{promoRules.map((item,index)=><div key={item[0]}><span className={`tone-${index===1?"violet":"blue"}`}><Gift size={15}/></span><div><strong>{item[0]}</strong><small>{item[1]}</small></div><label className="switch"><input type="checkbox" checked={enabled.has(index)} onChange={()=>setEnabled(current=>{const next=new Set(current);next.has(index)?next.delete(index):next.add(index);notify(`${item[0]}已${next.has(index)?"启用":"停用"}`);return next})}/><span/></label></div>)}</div></SectionCard>
      <SectionCard title="价格保护与异常预警" detail="监测叠加后成交价、退款和套利行为"><div className="price-alerts">{[["CPA 协议班成交价低于保护价","发现 3 笔叠加优惠，差额 ¥2,680","red"],["老学员券跨账号使用","关联设备 6 个，等待人工复核","amber"],["税务师试听券退款后已自动退券","今日处理 28 笔，规则运行正常","green"]].map(([title,detail,tone])=><button onClick={()=>notify(`已打开异常明细：${title}`)} key={title}><span className={`tone-${tone}`}><AlertTriangle size={15}/></span><div><strong>{title}</strong><small>{detail}</small></div><em>查看</em></button>)}</div></SectionCard>
      <SectionCard title="券核销与 ROI" detail="近 7 日使用趋势"><div className="marketing-chart"><ResponsiveContainer><BarChart data={activityTrend}><CartesianGrid vertical={false} stroke="rgb(var(--line))"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Bar dataKey="join" name="发放" fill="#93c5fd"/><Bar dataKey="revenue" name="核销" fill="#2563eb"/></BarChart></ResponsiveContainer></div></SectionCard>
    </div>
    <Modal open={createOpen} onClose={()=>setCreateOpen(false)} title="创建优惠券"><div className="form-grid"><label className="field form-span-2"><span>优惠券名称</span><input className="input" value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>券型</span><select className="select" value={type} onChange={e=>setType(e.target.value)}>{["满减券","折扣券","代金券","兑换券","运费券","礼品券","课程券"].map(item=><option key={item}>{item}</option>)}</select></label><label className="field"><span>优惠内容</span><input className="input" value={value} onChange={e=>setValue(e.target.value)}/></label><label className="field"><span>有效期</span><input className="input" type="date" defaultValue="2026-10-31"/></label><label className="field"><span>退款规则</span><select className="select"><option>退款自动退券</option><option>已使用不退券</option></select></label></div><div className="form-actions"><Button variant="secondary" onClick={()=>setCreateOpen(false)}>取消</Button><Button onClick={()=>{addCoupon(name,type,value);setCreateOpen(false)}}>创建</Button></div></Modal>
    <Modal open={Boolean(target)} onClose={()=>setTarget(null)} title="分群发放优惠券">{target&&<><div className="marketing-coupon-preview"><TicketPercent size={24}/><div><strong>{target.name}</strong><small>{target.value}</small></div></div><div className="form-grid"><label className="field"><span>发放方式</span><select className="select"><option>按人群分群</option><option>批量名单</option><option>自动触发</option><option>兑换码领取</option></select></label><label className="field"><span>目标人群</span><input className="input" value={audience} onChange={e=>setAudience(e.target.value)}/></label><label className="field"><span>预计发放</span><input className="input" type="number" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label className="field"><span>频控</span><select className="select"><option>每人限领 1 张</option><option>每月限领 1 张</option></select></label></div><p className="marketing-estimate">人群预估：{Math.round(amount*1.12).toLocaleString()} 人 · 排除免打扰与已领取用户后预计触达 {amount.toLocaleString()} 人</p><div className="form-actions"><Button variant="secondary" onClick={()=>setTarget(null)}>取消</Button><Button onClick={()=>{issueCoupon(target.id,amount);setTarget(null)}}><Send size={14}/>确认发放</Button></div></>}</Modal>
  </div>;
}
