import { useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, CalendarDays, CircleDollarSign, FileImage, FileText, Film, Link2, MessageSquareText, Plus, Radio, Send, Upload, UsersRound } from "lucide-react";
import { Badge, Button, Drawer, Modal } from "../../../components/ui";
import { trendData } from "../mockData";
import { useMarketing } from "../MarketingContext";
import type { Channel, ContentItem } from "../types";
import { ConfirmDialog, MarketingKpi, MiniStat, SectionCard } from "../components/MarketingShared";

export function ChannelsSection(){
  const {channels,updateChannelBudget,notify}=useMarketing();
  const [model,setModel]=useState("数据驱动归因");
  const [target,setTarget]=useState<Channel|null>(null);
  const [budget,setBudget]=useState(0);
  const [settle,setSettle]=useState<Channel|null>(null);
  return <div className="marketing-section">
    <div className="marketing-toolbar"><div className="segmented">{["渠道看板","推广追踪","A/B 落地页","结算付款"].map((item,index)=><button className={index===0?"active":""} onClick={()=>notify(`已切换至${item}`)} key={item}>{item}</button>)}</div><label>归因模型<select className="select" value={model} onChange={e=>{setModel(e.target.value);notify(`已切换为${e.target.value}`)}}>{["首次触点","末次触点","线性归因","时间衰减","数据驱动归因"].map(item=><option key={item}>{item}</option>)}</select></label><span className="spacer"/><Button variant="secondary" onClick={()=>notify("渠道登记表已打开，可录入联系人与计费模型")}><Plus size={14}/>登记渠道</Button></div>
    <div className="marketing-kpi-grid"><MarketingKpi label="渠道投入" value="¥ 88.3 万" detail="预算执行 85.7%" icon={CircleDollarSign}/><MarketingKpi label="渠道线索" value="20,280" detail="有效率 82.6%" icon={UsersRound} tone="green"/><MarketingKpi label="渠道付费" value="1,662" detail="平均转化 8.2%" icon={Link2}/><MarketingKpi label="综合 ROI" value="4.86" detail={`${model}口径`} icon={Radio}/></div>
    <div className="marketing-dashboard-grid">
      <SectionCard title="渠道投入产出趋势" detail="收入与成本 · 单位万元" className="wide"><div className="marketing-chart"><ResponsiveContainer><AreaChart data={trendData}><defs><linearGradient id="channelFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#10b981" stopOpacity=".22"/><stop offset="1" stopColor="#10b981" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="rgb(var(--line))"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Area dataKey="revenue" name="归因收入" stroke="#10b981" fill="url(#channelFill)" strokeWidth={2}/><Area dataKey="spend" name="渠道成本" stroke="#2563eb" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></SectionCard>
      <SectionCard title="触点路径贡献" detail="跨渠道用户旅程 · 前三条路径"><div className="touch-paths">{[["公众号","课程页","顾问企微","支付","31.8%"],["小红书","资料页","短信","支付","22.4%"],["图书扫码","试听课","顾问电话","支付","18.7%"]].map(path=><div key={path[0]}>{path.slice(0,4).map((item,index)=><span key={item}>{item}{index<3&&<i>→</i>}</span>)}<b>{path[4]}</b></div>)}</div></SectionCard>
    </div>
    <SectionCard title="渠道 ROI 与质量排名" detail="推广链接、UTM、来源识别、预算与结算统一管理"><div className="marketing-table-scroll"><table className="data-table marketing-table channel-table"><thead><tr><th>渠道 / 负责人</th><th>计费模型</th><th>预算消耗</th><th>曝光 / 点击</th><th>留资</th><th>付费</th><th>ROI</th><th>LTV</th><th>质量</th><th>操作</th></tr></thead><tbody>{channels.slice().sort((a,b)=>b.roi-a.roi).map(item=>{const rate=item.spent/item.budget*100;return <tr className={rate>100?"risk-row":""} key={item.id}><td><strong>{item.name}</strong><small>{item.owner} · {item.contact}</small></td><td>{item.model}</td><td><b>¥{item.spent.toLocaleString()}</b><small>预算 ¥{item.budget.toLocaleString()} · {rate.toFixed(0)}%</small><div className="progress"><span className={rate>95?"danger":""} style={{width:`${Math.min(rate,100)}%`}}/></div></td><td>{(item.leads*21).toLocaleString()} / {(item.leads*4).toLocaleString()}</td><td>{item.leads.toLocaleString()}</td><td>{item.paid}</td><td><b className="text-green">{item.roi}</b></td><td>¥{item.ltv.toLocaleString()}</td><td><Badge tone={item.quality==="S"?"green":item.quality==="A"?"blue":"amber"}>{item.quality} 级</Badge></td><td><div className="row-actions"><button onClick={()=>{setTarget(item);setBudget(item.budget)}}>预算</button><button onClick={()=>notify(`已复制 ${item.name} 专属链接、二维码与 UTM 参数`)}>推广码</button><button onClick={()=>setSettle(item)}>结算</button></div></td></tr>})}</tbody></table></div></SectionCard>
    <Modal open={Boolean(target)} onClose={()=>setTarget(null)} title="调整渠道预算">{target&&<><div className="marketing-stat-strip"><MiniStat label="当前预算" value={`¥${target.budget.toLocaleString()}`}/><MiniStat label="已消耗" value={`¥${target.spent.toLocaleString()}`}/><MiniStat label="剩余额度" value={`¥${Math.max(0,budget-target.spent).toLocaleString()}`}/></div><label className="field"><span>新预算金额</span><input className="input" type="number" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label>{budget<target.spent&&<p className="marketing-form-error"><AlertTriangle size={14}/>新预算不能低于已消耗金额。</p>}<div className="form-actions"><Button variant="secondary" onClick={()=>setTarget(null)}>取消</Button><Button disabled={budget<target.spent} onClick={()=>{updateChannelBudget(target.id,budget);setTarget(null)}}>保存预算</Button></div></>}</Modal>
    <ConfirmDialog open={Boolean(settle)} title="确认生成渠道结算单" detail={`将按 ${settle?.model} 规则为「${settle?.name}」生成 2026 年 9 月结算单，并进入财务付款流程。`} confirmLabel="生成并提交财务" onClose={()=>setSettle(null)} onConfirm={()=>notify("渠道结算单已生成并提交财务审批")}/>
  </div>;
}

const assets=[["CPA 审计冲刺蓝色海报","海报","1920×1080","使用 36 次"],["税务师讲师林岚半身照","讲师素材","4K PNG","使用 18 次"],["中级考后再战主视觉","活动 KV","3000×1688","使用 52 次"],["财经学习路径白皮书","PDF","8.6 MB","下载 2,680 次"]];
const contentIcons={文章:FileText,短视频:Film,直播:Radio,免费资料:FileImage,试听课:FileImage};

export function ContentSection(){
  const {content,advanceContent,notify}=useMarketing();
  const [view,setView]=useState("内容日历");
  const [preview,setPreview]=useState<ContentItem|null>(null);
  const [upload,setUpload]=useState(false);
  return <div className="marketing-section">
    <div className="marketing-toolbar"><div className="segmented">{["内容日历","素材库","海报工坊","讲师 IP"].map(item=><button className={view===item?"active":""} onClick={()=>setView(item)} key={item}>{item}</button>)}</div><span className="spacer"/><Button variant="secondary" onClick={()=>setUpload(true)}><Upload size={14}/>上传素材</Button><Button onClick={()=>notify("新选题已创建并加入 9 月内容日历")}><Plus size={14}/>新建选题</Button></div>
    <div className="marketing-kpi-grid"><MarketingKpi label="本月内容" value="86 条" detail="已发布 62 条" icon={FileText}/><MarketingKpi label="内容曝光" value="368.4 万" detail="环比 +24.6%" icon={Radio} tone="green"/><MarketingKpi label="内容线索" value="8,426" detail="资料类贡献 42%" icon={UsersRound}/><MarketingKpi label="讲师 IP" value="18 位" detail="本月直播 26 场" icon={Film} tone="violet"/></div>
    {view==="素材库"?<SectionCard title="营销素材库" detail="按格式、考试项目、渠道与使用记录管理"><div className="asset-library">{assets.map((item,index)=><button onClick={()=>notify(`正在预览：${item[0]}`)} key={item[0]}><span className={`tone-${index===1?"violet":index===3?"amber":"blue"}`}>{index===3?<FileText/>:<FileImage/>}</span><strong>{item[0]}</strong><small>{item[1]} · {item[2]}</small><em>{item[3]}</em></button>)}</div></SectionCard>:view==="海报工坊"?<PosterStudio notify={notify}/>:<div className="marketing-dashboard-grid"><SectionCard title="9 月内容日历" detail="从选题到发布的统一排期" className="wide"><div className="content-calendar">{["周一 14","周二 15","周三 16","周四 17","周五 18"].map((day,index)=><section key={day}><strong>{day}</strong>{content.filter((_,i)=>i%5===index).map(item=>{const Icon=contentIcons[item.type as keyof typeof contentIcons]??FileText;return <button onClick={()=>setPreview(item)} key={item.id}><Icon size={13}/><span>{item.title}</span><Badge tone={item.status==="已发布"?"green":item.status==="审核"?"amber":"blue"}>{item.status}</Badge></button>})}</section>)}</div></SectionCard><SectionCard title="内容效能排行" detail="按带来线索排序"><div className="content-rank">{content.filter(item=>item.status==="已发布").map(item=><div key={item.id}><span className="tone-blue"><ContentTypeIcon type={item.type} size={15}/></span><div><strong>{item.title}</strong><small>{item.channel} · {item.views.toLocaleString()} 次浏览</small></div><b>{item.leads} 线索</b></div>)}</div></SectionCard><SectionCard title="讲师 IP 数据" detail="内容影响与转化贡献"><div className="marketing-chart"><ResponsiveContainer><BarChart data={[{name:"韩老师",fans:86,leads:1280},{name:"林老师",fans:72,leads:960},{name:"赵老师",fans:64,leads:816},{name:"周老师",fans:58,leads:680}]}><CartesianGrid vertical={false} stroke="rgb(var(--line))"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="leads" name="带来线索" fill="#8b5cf6" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></SectionCard></div>}
    <Drawer open={Boolean(preview)} onClose={()=>setPreview(null)} title="内容详情与排期">{preview&&<><div className="content-preview"><span className="tone-blue"><ContentTypeIcon type={preview.type} size={24}/></span><Badge tone={preview.status==="已发布"?"green":"blue"}>{preview.status}</Badge><h2>{preview.title}</h2><p>{preview.type} · {preview.channel} · 负责人 {preview.owner} · 排期 2026-{preview.date}</p></div><div className="marketing-stat-strip"><MiniStat label="浏览" value={preview.views.toLocaleString()}/><MiniStat label="带来线索" value={preview.leads.toLocaleString()}/><MiniStat label="线索转化" value={preview.views?`${(preview.leads/preview.views*100).toFixed(1)}%`:"待发布"}/></div><div className="form-actions"><Button variant="secondary" onClick={()=>notify("发布提醒已发送给负责人")}>提醒负责人</Button>{preview.status!=="已发布"&&<Button onClick={()=>{advanceContent(preview.id);setPreview(null)}}>推进至下一状态</Button>}</div></>}</Drawer>
    <Modal open={upload} onClose={()=>setUpload(false)} title="上传营销素材"><label className="marketing-dropzone"><Upload size={24}/><strong>选择素材文件</strong><small>支持 PNG、JPG、MP4、PDF，单文件不超过 200 MB</small><input type="file" onChange={e=>e.target.files?.length&&notify(`已选择素材：${e.target.files[0].name}`)}/></label><div className="form-grid"><label className="field"><span>素材分类</span><select className="select"><option>活动海报</option><option>讲师素材</option><option>课程资料</option></select></label><label className="field"><span>标签</span><input className="input" placeholder="CPA、冲刺、蓝色"/></label></div><div className="form-actions"><Button onClick={()=>{setUpload(false);notify("素材已上传并完成智能标签识别")}}>确认上传</Button></div></Modal>
  </div>;
}

function ContentTypeIcon({type,size}:{type:string;size:number}) {
  const Icon=contentIcons[type as keyof typeof contentIcons]??FileText;
  return <Icon size={size}/>;
}

function PosterStudio({notify}:{notify:(message:string)=>void}){const [color,setColor]=useState("#2563eb");return <SectionCard title="渠道海报在线工坊" detail="调整主标题、权益与渠道规格后生成版本"><div className="poster-studio"><aside><label className="field"><span>主标题</span><input className="input" defaultValue="CPA 全科联报冲刺季"/></label><label className="field"><span>核心权益</span><input className="input" defaultValue="限时立减 2000 元"/></label><label className="field"><span>品牌色</span><input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label className="field"><span>渠道规格</span><select className="select"><option>公众号首图 900×383</option><option>小红书 3:4</option><option>抖音竖版 9:16</option></select></label><Button onClick={()=>notify("已生成公众号、小红书与抖音 3 个渠道版本")}>生成渠道版本</Button></aside><div className="poster-canvas" style={{background:color}}><small>高顿财经 · 2026</small><strong>CPA 全科联报<br/>冲刺季</strong><span>限时立减 ¥2,000</span><em>扫码领取专属学习方案</em></div></div></SectionCard>}

export function MessagesSection(){
  const {messages,addMessage,notify}=useMarketing();
  const [channel,setChannel]=useState("全部");
  const [create,setCreate]=useState(false);
  const [form,setForm]=useState({name:"税务师准考证提醒",channel:"短信" as "短信"|"邮件"|"微信"|"Push",audience:"税务师已报名未打印准考证"});
  const rows=useMemo(()=>messages.filter(item=>channel==="全部"||item.channel===channel),[messages,channel]);
  return <div className="marketing-section">
    <div className="marketing-toolbar"><div className="segmented">{["全部","短信","邮件","微信","Push"].map(item=><button className={channel===item?"active":""} onClick={()=>setChannel(item)} key={item}>{item}</button>)}</div><span className="spacer"/><Button variant="secondary" onClick={()=>notify("已打开触达模板库：欢迎、考试、续费、唤醒 SOP")}>模板与 SOP</Button><Button onClick={()=>setCreate(true)}><Plus size={14}/>创建触达任务</Button></div>
    <div className="marketing-kpi-grid"><MarketingKpi label="本月发送" value="86.4 万" detail="频控拦截 2.8 万" icon={Send}/><MarketingKpi label="平均打开率" value="52.3%" detail="微信渠道最高" icon={MessageSquareText} tone="green"/><MarketingKpi label="触达转化" value="9.8%" detail="带来付费 1,286" icon={CircleDollarSign}/><MarketingKpi label="退订 / 免扰" value="0.42%" detail="低于警戒线" icon={AlertTriangle} tone="amber"/></div>
    <div className="marketing-dashboard-grid"><SectionCard title="触达效果趋势" detail="发送、打开与转化"><div className="marketing-chart"><ResponsiveContainer><AreaChart data={trendData}><CartesianGrid vertical={false} stroke="rgb(var(--line))"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Area dataKey="leads" name="送达" stroke="#2563eb" fill="#dbeafe"/><Area dataKey="paid" name="转化" stroke="#10b981" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></SectionCard><SectionCard title="自动触达 SOP" detail="按学员生命周期自动执行"><div className="sop-list">{[["新学员欢迎","报名后 10 分钟","短信 + 微信","运行中"],["考试提醒","考前 30/7/1 天","微信 + Push","运行中"],["续费提醒","到期前 30 天","短信 + 顾问任务","运行中"],["沉睡激活","连续 7 天未学","Push + 优惠券","优化中"]].map(item=><button onClick={()=>notify(`已打开 SOP：${item[0]}`)} key={item[0]}><span><Radio size={15}/></span><div><strong>{item[0]}</strong><small>{item[1]} · {item[2]}</small></div><Badge tone={item[3]==="运行中"?"green":"amber"}>{item[3]}</Badge></button>)}</div></SectionCard></div>
    <SectionCard title="发送任务与效果" detail={`${rows.length} 个任务 · 已排除退订、免打扰与超频用户`}><div className="marketing-table-scroll"><table className="data-table marketing-table"><thead><tr><th>任务</th><th>渠道</th><th>目标人群</th><th>发送时间</th><th>已发送</th><th>打开率</th><th>转化率</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map(item=><tr key={item.id}><td><strong>{item.name}</strong><small>{item.id}</small></td><td><Badge tone={item.channel==="微信"?"green":item.channel==="Push"?"violet":"blue"}>{item.channel}</Badge></td><td>{item.audience}</td><td>{item.schedule}</td><td>{item.sent.toLocaleString()}</td><td>{item.openRate||"-"}{item.openRate?"%":""}</td><td>{item.conversion||"-"}{item.conversion?"%":""}</td><td><Badge tone={item.status==="已完成"?"green":item.status==="发送中"?"blue":item.status==="待发送"?"amber":"neutral"}>{item.status}</Badge></td><td><button className="link" onClick={()=>notify(`已复制任务「${item.name}」为草稿`)}>复制</button></td></tr>)}</tbody></table></div></SectionCard>
    <Modal open={create} onClose={()=>setCreate(false)} title="创建触达任务"><div className="form-grid"><label className="field form-span-2"><span>任务名称</span><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field"><span>发送渠道</span><select className="select" value={form.channel} onChange={e=>setForm({...form,channel:e.target.value as typeof form.channel})}>{["短信","邮件","微信","Push"].map(item=><option key={item}>{item}</option>)}</select></label><label className="field"><span>目标人群</span><input className="input" value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}/></label><label className="field"><span>发送策略</span><select className="select"><option>立即发送</option><option>定时发送</option><option>用户最佳时机</option></select></label><label className="field"><span>A/B 测试</span><select className="select"><option>开启，流量各 50%</option><option>不开启</option></select></label><label className="field form-span-2"><span>消息内容</span><textarea defaultValue={"${学员姓名}，税务师准考证已开放打印。点击 ${短链} 查看考点提醒与冲刺资料。"} /></label></div><div className="marketing-estimate">人群预估 18,620 人 · 频控排除 328 人 · 免打扰排除 116 人 · 预计可发送 18,176 人</div><div className="form-actions"><Button variant="secondary" onClick={()=>notify("测试消息已发送至当前账号")}>发送测试</Button><Button onClick={()=>{addMessage(form.name,form.channel,form.audience);setCreate(false)}}>创建任务</Button></div></Modal>
  </div>;
}
