import { useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Award, BarChart3, Bell, CheckCircle2, CircleDollarSign, Download, Eye, FileText, Flame, Gift, Monitor, Plus, Save, Smartphone, Star, Store, UsersRound } from "lucide-react";
import { Badge, Button, Drawer, Modal } from "../../../components/ui";
import { funnelData, trendData } from "../mockData";
import { useMarketing } from "../MarketingContext";
import type { LandingPage, LoyaltyTier } from "../types";
import { ConfirmDialog, MarketingKpi, MiniStat, SectionCard } from "../components/MarketingShared";

export function PagesSection(){
  const {pages,publishPage,notify}=useMarketing();
  const [editor,setEditor]=useState<LandingPage|null>(null);
  const [device,setDevice]=useState<"desktop"|"mobile">("desktop");
  const [blocks,setBlocks]=useState(["首屏课程权益","讲师阵容","课程大纲","限时优惠","留资表单"]);
  const [selected,setSelected]=useState(0);
  const [confirm,setConfirm]=useState<LandingPage|null>(null);
  const [records,setRecords]=useState(false);
  return <div className="marketing-section">
    <div className="marketing-toolbar"><div className="segmented">{["页面列表","模板库","表单管理","提交记录","A/B 实验"].map((item,index)=><button className={index===0?"active":""} onClick={()=>item==="提交记录"?setRecords(true):notify(`已切换至${item}`)} key={item}>{item}</button>)}</div><span className="spacer"/><Button onClick={()=>notify("已从「课程转化型」模板创建页面草稿")}><Plus size={14}/>新建落地页</Button></div>
    <div className="marketing-kpi-grid"><MarketingKpi label="在线页面" value="18 个" detail="本月发布 6 个" icon={Monitor}/><MarketingKpi label="总访问 UV" value="24.8 万" detail="环比 +18.6%" icon={Eye} tone="green"/><MarketingKpi label="表单留资" value="19,940" detail="平均转化 8.0%" icon={FileText}/><MarketingKpi label="A/B 实验" value="6 组" detail="3 组已选出优胜版" icon={BarChart3} tone="violet"/></div>
    <SectionCard title="落地页与表单" detail="审批、定时发布、SEO 与转化数据统一管理"><div className="marketing-table-scroll"><table className="data-table marketing-table"><thead><tr><th>页面</th><th>模板</th><th>负责人</th><th>最近更新</th><th>PV / UV</th><th>留资</th><th>转化率</th><th>状态</th><th>操作</th></tr></thead><tbody>{pages.map(item=><tr key={item.id}><td><strong>{item.name}</strong><small>{item.id} · /campaign/{item.id.toLowerCase()}</small></td><td>{item.template}</td><td>{item.owner}</td><td>{item.updatedAt}</td><td>{item.pv.toLocaleString()} / {item.uv.toLocaleString()}</td><td>{item.leads.toLocaleString()}</td><td>{item.uv?(item.leads/item.uv*100).toFixed(1):"-"}{item.uv?"%":""}</td><td><Badge tone={item.status==="已发布"?"green":item.status==="待审批"?"amber":"neutral"}>{item.status}</Badge></td><td><div className="row-actions"><button onClick={()=>{setEditor(item);setBlocks(["首屏课程权益","讲师阵容","课程大纲","限时优惠","留资表单"])}}>编辑</button><button onClick={()=>notify(`已打开「${item.name}」热力图与转化漏斗`)}>分析</button>{item.status!=="已发布"&&<button onClick={()=>setConfirm(item)}>发布</button>}</div></td></tr>)}</tbody></table></div></SectionCard>
    <Drawer open={Boolean(editor)} onClose={()=>setEditor(null)} title="落地页可视化编辑器" wide>{editor&&<div className="page-editor"><div className="page-editor-toolbar"><div className="segmented"><button className={device==="desktop"?"active":""} onClick={()=>setDevice("desktop")}><Monitor size={13}/>桌面</button><button className={device==="mobile"?"active":""} onClick={()=>setDevice("mobile")}><Smartphone size={13}/>移动</button></div><span>自动保存于刚刚</span><Button variant="secondary" onClick={()=>notify("预览链接已生成并复制")}><Eye size={14}/>预览</Button><Button onClick={()=>notify("页面草稿已保存")}><Save size={14}/>保存</Button></div><div className="page-builder"><aside><strong>组件库</strong>{["标题文本","图片素材","讲师卡片","课程大纲","倒计时","优惠权益","留资表单","常见问题"].map(item=><button onClick={()=>setBlocks(items=>[...items,item])} key={item}><Plus size={12}/>{item}</button>)}</aside><main className={device}>{blocks.map((block,index)=><button className={selected===index?"selected":""} onClick={()=>setSelected(index)} key={`${block}-${index}`}><span>{block}</span><small>{block==="留资表单"?"姓名 · 手机号 · 意向课程":"点击编辑组件内容"}</small></button>)}</main><aside className="properties"><strong>属性设置</strong><label className="field"><span>组件名称</span><input className="input" value={blocks[selected]??""} onChange={e=>setBlocks(items=>items.map((item,index)=>index===selected?e.target.value:item))}/></label><label><input type="checkbox" defaultChecked/>设为必填</label><label><input type="checkbox" defaultChecked/>开启手机号校验</label><label><input type="checkbox" defaultChecked/>重复提交检测</label><label><input type="checkbox" defaultChecked/>设备指纹防刷</label><Button variant="danger" disabled={blocks.length<=1} onClick={()=>{setBlocks(items=>items.filter((_,index)=>index!==selected));setSelected(0)}}>删除组件</Button></aside></div></div>}</Drawer>
    <Drawer open={records} onClose={()=>setRecords(false)} title="表单提交记录" wide><div className="marketing-stat-strip"><MiniStat label="今日提交" value="1,286"/><MiniStat label="重复拦截" value="86"/><MiniStat label="防刷拦截" value="23"/><MiniStat label="手机号有效" value="98.2%"/></div><div className="marketing-table-scroll"><table className="data-table"><thead><tr><th>提交时间</th><th>姓名</th><th>手机号</th><th>意向课程</th><th>来源</th><th>状态</th></tr></thead><tbody>{[["14:32","王*","138****5621","CPA 全科","公众号","已分配"],["14:28","李*","186****2940","税务师","抖音","已分配"],["14:21","周*","159****7832","中级会计","小红书","重复拦截"]].map(row=><tr key={row[1]+row[0]}>{row.map((cell,index)=><td key={cell}>{index===5?<Badge tone={cell==="已分配"?"green":"amber"}>{cell}</Badge>:cell}</td>)}</tr>)}</tbody></table></div></Drawer>
    <ConfirmDialog open={Boolean(confirm)} title="确认发布落地页" detail={`发布「${confirm?.name}」后，当前草稿将成为线上版本；系统将执行 SEO、表单校验和防刷检查。`} confirmLabel="检查并发布" onClose={()=>setConfirm(null)} onConfirm={()=>confirm&&publishPage(confirm.id)}/>
  </div>;
}

export function LoyaltySection(){
  const {tiers,pointsRate,setPointsRate,updateTier,notify}=useMarketing();
  const [edit,setEdit]=useState<LoyaltyTier|null>(null);
  const [threshold,setThreshold]=useState(0);
  const [rate,setRate]=useState(pointsRate);
  return <div className="marketing-section">
    <div className="marketing-toolbar"><div className="segmented">{["会员等级","积分规则","积分商城","成长任务","徽章体系"].map((item,index)=><button className={index===0?"active":""} onClick={()=>notify(`已切换至${item}`)} key={item}>{item}</button>)}</div><span className="spacer"/><Button variant="secondary" onClick={()=>notify("积分过期提醒已发送给 3,826 位会员")}><Bell size={14}/>过期提醒</Button><Button onClick={()=>notify("积分商城已新增「CPA 冲刺题库兑换券」商品")}><Plus size={14}/>新增兑换商品</Button></div>
    <div className="marketing-kpi-grid"><MarketingKpi label="会员总数" value="75,266" detail="付费会员 26,986" icon={UsersRound}/><MarketingKpi label="会员复购率" value="32.8%" detail="普通用户 14.2%" icon={Star} tone="green"/><MarketingKpi label="积分余额" value="2,864 万" detail="90 天内过期 186 万" icon={Gift} tone="amber"/><MarketingKpi label="会员 ROI" value="7.42" detail="客单价 ¥8,680" icon={CircleDollarSign}/></div>
    <div className="marketing-dashboard-grid">
      <SectionCard title="会员等级体系" detail="成长值门槛、权益、升降级与保护期" className="wide"><div className="tier-grid">{tiers.map((tier,index)=><button className={`tier-card tier-${index}`} onClick={()=>{setEdit(tier);setThreshold(tier.threshold)}} key={tier.id}><span><Award size={18}/></span><small>{tier.id}</small><strong>{tier.name}</strong><b>{tier.members.toLocaleString()} 人</b><p>成长值 ≥ {tier.threshold.toLocaleString()}</p><em>{tier.discount} · 保护期 {tier.protectionDays} 天</em><div>{tier.benefits.map(item=><Badge tone={index>2?"violet":"blue"} key={item}>{item}</Badge>)}</div></button>)}</div></SectionCard>
      <SectionCard title="会员消费与复购" detail="各等级年均消费"><div className="marketing-chart"><ResponsiveContainer><BarChart data={tiers.map((item,index)=>({name:item.name,value:1800+index*5600}))}><CartesianGrid vertical={false} stroke="rgb(var(--line))"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="value" name="年均消费" fill="#2563eb" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></SectionCard>
      <SectionCard title="积分运营规则" detail="获取、消耗与过期策略"><div className="points-rule"><span className="tone-amber"><Gift size={20}/></span><div><strong>消费积分</strong><p>每消费 ¥1 获取 <b>{rate}</b> 积分，积分有效期 24 个月。</p></div><label><input type="number" min="1" max="100" value={rate} onChange={e=>setRate(Number(e.target.value))}/><span>积分 / 元</span></label><Button onClick={()=>setPointsRate(rate)}>保存规则</Button></div><div className="task-rewards">{[["连续签到 7 天","+200","3,286 人完成"],["完成 10 节课程","+500","1,862 人完成"],["分享学习报告","+80","6,420 人完成"]].map(item=><button onClick={()=>notify(`已打开任务配置：${item[0]}`)} key={item[0]}><Flame size={15}/><span><strong>{item[0]}</strong><small>{item[2]}</small></span><b>{item[1]}</b></button>)}</div></SectionCard>
      <SectionCard title="积分商城" detail="库存、兑换与履约"><div className="mall-list">{[["CPA 冲刺题库 30 天","12,000 积分","库存 286"],["讲师 1v1 规划 30 分钟","28,000 积分","库存 42"],["高顿财经定制笔记本","8,000 积分","库存 628"]].map((item,index)=><button onClick={()=>notify(`已打开库存配置：${item[0]}`)} key={item[0]}><span className={`tone-${index===1?"violet":"blue"}`}><Store size={16}/></span><div><strong>{item[0]}</strong><small>{item[2]}</small></div><b>{item[1]}</b></button>)}</div></SectionCard>
    </div>
    <Modal open={Boolean(edit)} onClose={()=>setEdit(null)} title="调整会员等级">{edit&&<><div className="marketing-coupon-preview"><Award size={24}/><div><strong>{edit.name}</strong><small>{edit.members.toLocaleString()} 位当前会员 · {edit.discount}</small></div></div><label className="field"><span>成长值门槛</span><input className="input" type="number" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label><label className="field"><span>升级保护期</span><select className="select" defaultValue={edit.protectionDays}><option value="30">30 天</option><option value="60">60 天</option><option value="90">90 天</option><option value="180">180 天</option></select></label><div className="form-actions"><Button variant="secondary" onClick={()=>setEdit(null)}>取消</Button><Button onClick={()=>{updateTier(edit.id,threshold);setEdit(null)}}>保存等级</Button></div></>}</Modal>
  </div>;
}

export function MarketingAnalyticsSection(){
  const {channels,notify}=useMarketing();
  const [report,setReport]=useState("营销大盘");
  const [realtime,setRealtime]=useState(false);
  const [subscribe,setSubscribe]=useState(false);
  const reportTypes=["营销大盘","活动分析","渠道分析","内容分析","消息分析","裂变分析","优惠券分析"];
  const exportCsv=()=>{const csv=`渠道,线索,付费,ROI\n${channels.map(item=>`${item.name},${item.leads},${item.paid},${item.roi}`).join("\n")}`;const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="marketing-analysis-2026-09.csv";link.click();URL.revokeObjectURL(link.href);notify("营销分析 CSV 已导出");};
  return <div className={`marketing-section ${realtime?"realtime-mode":""}`}>
    <div className="marketing-toolbar"><div className="segmented report-tabs">{reportTypes.map(item=><button className={report===item?"active":""} onClick={()=>setReport(item)} key={item}>{item}</button>)}</div><span className="spacer"/><Button variant="secondary" onClick={()=>setSubscribe(true)}><Bell size={14}/>订阅</Button><Button variant="secondary" onClick={exportCsv}><Download size={14}/>CSV</Button><Button variant="secondary" onClick={()=>window.print()}>PDF / 打印</Button><Button onClick={()=>setRealtime(!realtime)}>{realtime?"退出大屏":"实时大屏"}</Button></div>
    {realtime&&<div className="realtime-banner"><span><i/>实时数据流已连接</span><strong>营销指挥大屏 · 2026-09-15 14:36:28</strong><Badge tone="red">2 项异常</Badge></div>}
    <div className="marketing-kpi-grid six"><MarketingKpi label="实时曝光" value="128.6 万" detail="今日累计" icon={Eye}/><MarketingKpi label="实时访问" value="86,420" detail="峰值 3,826 /min" icon={BarChart3}/><MarketingKpi label="新增线索" value="8,624" detail="有效率 86.2%" icon={UsersRound} tone="green"/><MarketingKpi label="付费学员" value="986" detail="转化率 11.4%" icon={CheckCircle2}/><MarketingKpi label="营销收入" value="¥ 286.4 万" detail="今日归因" icon={CircleDollarSign} tone="green"/><MarketingKpi label="预测 ROI" value="4.68" detail="置信区间 4.4-4.9" icon={Star} tone="violet"/></div>
    <div className="marketing-dashboard-grid">
      <SectionCard title={`${report}趋势`} detail="投入、收入与预测区间" className="wide"><div className="marketing-chart large"><ResponsiveContainer><AreaChart data={trendData}><defs><linearGradient id="analyticsRevenue" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2563eb" stopOpacity=".28"/><stop offset="1" stopColor="#2563eb" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="rgb(var(--line))"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Area dataKey="revenue" name="收入" stroke="#2563eb" fill="url(#analyticsRevenue)" strokeWidth={2.4}/><Area dataKey="spend" name="投入" stroke="#f59e0b" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></SectionCard>
      <SectionCard title="全链路漏斗" detail="曝光 → 续费 · 点击节点可下钻"><div className="analytics-funnel">{funnelData.map((item,index)=><button onClick={()=>notify(`已下钻至「${item.name}」阶段明细`)} style={{width:`${100-index*5.4}%`}} key={item.name}><span>{item.name}</span><strong>{item.value.toLocaleString()}</strong><small>{index?`${(item.value/funnelData[index-1].value*100).toFixed(1)}%`:"100%"}</small></button>)}</div></SectionCard>
      <SectionCard title="高价值用户画像" detail="预测 LTV ≥ ¥20,000"><div className="profile-cloud">{[["28-36 岁在职财务","72%"],["CPA + 中级双证意向","58%"],["公众号深度阅读","46%"],["已购买财经图书","41%"],["金卡及以上会员","36%"],["一线及新一线城市","68%"]].map(item=><span key={item[0]}><strong>{item[1]}</strong>{item[0]}</span>)}</div></SectionCard>
      <SectionCard title="渠道 ROI 排名与预测" detail="数据驱动归因"><div className="roi-forecast">{channels.slice().sort((a,b)=>b.roi-a.roi).map((item,index)=><div key={item.id}><b>{index+1}</b><span>{item.name}</span><em>{item.roi}</em><small>预测 {(item.roi*(1+(index%3-1)*.04)).toFixed(2)}</small></div>)}</div></SectionCard>
    </div>
    <SectionCard title="自定义报表" detail="已保存口径与自动订阅"><div className="saved-reports">{[["渠道周度 ROI 复盘","每周一 09:00","市场负责人、财务 BP"],["考试节点转化日报","每天 18:00","营销运营、销售主管"],["会员复购月报","每月 1 日","会员运营、业务负责人"]].map(item=><button onClick={()=>notify(`已打开报表：${item[0]}`)} key={item[0]}><FileText size={16}/><span><strong>{item[0]}</strong><small>{item[1]} · {item[2]}</small></span><Badge tone="green">订阅中</Badge></button>)}</div></SectionCard>
    <Modal open={subscribe} onClose={()=>setSubscribe(false)} title="订阅营销报表"><div className="form-grid"><label className="field"><span>报表</span><select className="select">{reportTypes.map(item=><option key={item}>{item}</option>)}</select></label><label className="field"><span>频率</span><select className="select"><option>每日 18:00</option><option>每周一 09:00</option><option>每月 1 日</option></select></label><label className="field form-span-2"><span>接收人</span><input className="input" defaultValue="市场负责人、财务 BP、销售主管"/></label><label className="field"><span>格式</span><select className="select"><option>PDF + 在线链接</option><option>Excel</option></select></label><label className="field"><span>异常提醒</span><select className="select"><option>ROI 低于 3.0 时提醒</option><option>不提醒</option></select></label></div><div className="form-actions"><Button onClick={()=>{setSubscribe(false);notify("营销报表订阅已保存")}}>保存订阅</Button></div></Modal>
  </div>;
}
