import { useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, Bot, CheckCircle2, CircleDollarSign, Copy, GitBranch, Gift, Pause, Play, Plus, Share2, ShieldCheck, Timer, Trash2, UsersRound, Zap } from "lucide-react";
import { Badge, Button, Drawer } from "../../../components/ui";
import { useMarketing } from "../MarketingContext";
import type { AutomationFlow, Referral } from "../types";
import { ConfirmDialog, MarketingKpi, MiniStat, SectionCard } from "../components/MarketingShared";

export function ReferralsSection(){
  const {referrals,approveReward,notify}=useMarketing();
  const [detail,setDetail]=useState<Referral|null>(null);
  const [confirm,setConfirm]=useState<Referral|null>(null);
  const [antiFraud,setAntiFraud]=useState(true);
  return <div className="marketing-section">
    <div className="marketing-toolbar"><div className="segmented">{["推荐有礼","拼团砍价","助力活动","分销佣金","奖励记录"].map((item,index)=><button className={index===0?"active":""} onClick={()=>notify(`已切换至${item}`)} key={item}>{item}</button>)}</div><span className="spacer"/><label className="inline-switch"><span>反作弊规则</span><span className="switch"><input type="checkbox" checked={antiFraud} onChange={()=>{setAntiFraud(!antiFraud);notify(`反作弊规则已${antiFraud?"暂停":"启用"}`)}}/><span/></span></label><Button onClick={()=>notify("裂变活动草稿已创建，可配置双边奖励")}><Plus size={14}/>创建裂变活动</Button></div>
    <div className="marketing-kpi-grid"><MarketingKpi label="裂变参与" value="13,706" detail="分享率 46.8%" icon={Share2}/><MarketingKpi label="带来新客" value="2,794" detail="近 30 天 +18.2%" icon={UsersRound} tone="green"/><MarketingKpi label="平均 K 因子" value="1.62" detail="病毒周期 3.8 天" icon={Zap} tone="violet"/><MarketingKpi label="裂变 ROI" value="6.28" detail="获客成本 ¥186" icon={CircleDollarSign}/></div>
    <div className="marketing-dashboard-grid"><SectionCard title="裂变增长趋势" detail="参与、分享与成功转化"><div className="marketing-chart"><ResponsiveContainer><BarChart data={[{d:"09-01",share:680,paid:118},{d:"09-04",share:920,paid:186},{d:"09-07",share:1280,paid:248},{d:"09-10",share:1680,paid:326},{d:"09-13",share:2180,paid:468}]}><CartesianGrid vertical={false} stroke="rgb(var(--line))"/><XAxis dataKey="d"/><YAxis/><Tooltip/><Bar dataKey="share" name="分享" fill="#8b5cf6"/><Bar dataKey="paid" name="转化" fill="#10b981"/></BarChart></ResponsiveContainer></div></SectionCard><SectionCard title="关系绑定与反作弊" detail="设备、手机号、支付账户与行为联合识别"><div className="fraud-summary"><span className="tone-green"><ShieldCheck size={22}/></span><div><strong>98.7% 推荐关系可信</strong><p>今日识别异常关系 28 条，已冻结奖励 16 笔。</p></div></div>{[["同设备批量注册","12 条","高风险"],["支付账户重复","9 条","中风险"],["短时异常助力","7 条","中风险"]].map(item=><button onClick={()=>notify(`已打开${item[0]}证据链`)} key={item[0]}><span>{item[0]}</span><b>{item[1]}</b><Badge tone={item[2]==="高风险"?"red":"amber"}>{item[2]}</Badge></button>)}</SectionCard></div>
    <SectionCard title="裂变活动与奖励" detail="双边奖励、佣金和未使用提醒统一管理"><div className="marketing-table-scroll"><table className="data-table marketing-table"><thead><tr><th>活动</th><th>玩法</th><th>奖励</th><th>参与</th><th>转化</th><th>K 因子</th><th>ROI</th><th>状态</th><th>操作</th></tr></thead><tbody>{referrals.map(item=><tr key={item.id}><td><strong>{item.name}</strong><small>{item.id}</small></td><td>{item.type}</td><td>{item.reward}</td><td>{item.participants.toLocaleString()}</td><td>{item.conversions.toLocaleString()}</td><td><b>{item.kFactor}</b></td><td>{item.roi}</td><td><Badge tone={item.status==="进行中"?"green":item.status==="待审核"?"amber":"neutral"}>{item.status}</Badge></td><td><div className="row-actions"><button onClick={()=>setDetail(item)}>明细</button>{item.status==="待审核"&&<button onClick={()=>setConfirm(item)}>审核发放</button>}<button onClick={()=>notify(`已向 ${Math.round(item.participants*.18)} 位用户发送奖励未使用提醒`)}>提醒</button></div></td></tr>)}</tbody></table></div></SectionCard>
    <Drawer open={Boolean(detail)} onClose={()=>setDetail(null)} title="推荐关系与奖励记录">{detail&&<><div className="marketing-stat-strip"><MiniStat label="推荐人" value={detail.participants.toLocaleString()}/><MiniStat label="成功绑定" value={Math.round(detail.participants*.72).toLocaleString()}/><MiniStat label="成功转化" value={detail.conversions.toLocaleString()}/><MiniStat label="待发奖励" value="86 笔"/></div><div className="reward-records">{["陈* → 王* · CPA 全科联报","李* → 周* · 中级精品班","张* → 孙* · 税务师冲刺营","许* → 林* · 财管单科班"].map((item,index)=><div key={item}><span className="tone-violet"><Gift size={15}/></span><div><strong>{item}</strong><small>关系绑定于 09-{15-index} · 设备与支付校验通过</small></div><Badge tone={index===0?"amber":"green"}>{index===0?"待发放":"已发放"}</Badge></div>)}</div></>}</Drawer>
    <ConfirmDialog open={Boolean(confirm)} title="确认审核并发放奖励" detail={`将为「${confirm?.name}」通过的推荐关系发放奖励，佣金类奖励将同步进入财务结算。`} confirmLabel="审核通过并发放" onClose={()=>setConfirm(null)} onConfirm={()=>confirm&&approveReward(confirm.id)}/>
  </div>;
}

const nodeMeta:Record<string,{icon:typeof Zap;tone:string}>={"触发":{icon:Zap,tone:"blue"},"条件":{icon:GitBranch,tone:"amber"},"等待":{icon:Timer,tone:"violet"},"动作":{icon:Play,tone:"green"},"分支":{icon:GitBranch,tone:"violet"}};

export function AutomationSection(){
  const {flows,toggleFlow,updateFlowNodes,notify}=useMarketing();
  const [selected,setSelected]=useState<AutomationFlow>(flows[0]);
  const [nodes,setNodes]=useState(selected.nodes);
  const [traffic,setTraffic]=useState(50);
  const [confirm,setConfirm]=useState<AutomationFlow|null>(null);
  const selectFlow=(flow:AutomationFlow)=>{setSelected(flow);setNodes(flow.nodes)};
  const nodeKind=(label:string)=>Object.keys(nodeMeta).find(key=>label.includes(key))??(label.includes("微信")||label.includes("短信")||label.includes("Push")||label.includes("推荐")||label.includes("优惠")||label.includes("顾问")?"动作":"条件");
  return <div className="marketing-section">
    <div className="marketing-toolbar"><div className="segmented">{["流程画布","模板库","运行日志","版本管理","A/B 实验"].map((item,index)=><button className={index===0?"active":""} onClick={()=>notify(`已切换至${item}`)} key={item}>{item}</button>)}</div><span className="spacer"/><Button variant="secondary" onClick={()=>notify(`已复制「${selected.name}」为新草稿`)}><Copy size={14}/>复制流程</Button><Button onClick={()=>notify("已从「考后再战」模板创建自动化流程")}><Plus size={14}/>新建流程</Button></div>
    <div className="marketing-automation-layout">
      <SectionCard title="自动化流程" detail={`${flows.filter(item=>item.active).length} 个运行中`} className="flow-list-card"><div className="flow-list">{flows.map(flow=><button className={selected.id===flow.id?"active":""} onClick={()=>selectFlow(flow)} key={flow.id}><span className={`tone-${flow.active?"violet":"neutral"}`}><Bot size={16}/></span><div><strong>{flow.name}</strong><small>{flow.trigger}</small><em>{flow.version} · 执行 {flow.executions.toLocaleString()} 次</em></div><Badge tone={flow.errors?"red":flow.active?"green":"neutral"}>{flow.errors?`${flow.errors} 异常`:flow.active?"运行中":"已暂停"}</Badge></button>)}</div></SectionCard>
      <SectionCard title={selected.name} detail={`${selected.version} · ${selected.trigger}`} actions={<><Button variant="secondary" onClick={()=>notify("已打开流程运行日志")}>查看日志</Button><Button variant={selected.active?"danger":"primary"} onClick={()=>selected.active?setConfirm(selected):toggleFlow(selected.id)}>{selected.active?<><Pause size={14}/>暂停</>:<><Play size={14}/>启用</>}</Button></>} className="flow-canvas-card">
        <div className="flow-canvas">{nodes.map((node,index)=>{const kind=nodeKind(node);const Meta=nodeMeta[kind];const Icon=Meta.icon;return <div className="flow-node-wrap" key={`${node}-${index}`}><article className={`flow-node ${kind==="触发"?"start":""}`}><span className={`tone-${Meta.tone}`}><Icon size={16}/></span><div><small>{kind}节点</small><strong>{node}</strong></div>{index>0&&<button aria-label={`删除${node}`} onClick={()=>setNodes(items=>items.filter((_,i)=>i!==index))}><Trash2 size={13}/></button>}</article>{index<nodes.length-1&&<span className="flow-connector">↓</span>}</div>})}<div className="flow-add-row">{["条件","动作","等待","分支"].map(item=><button onClick={()=>setNodes(items=>[...items,`${item}：待配置`])} key={item}><Plus size={12}/>{item}</button>)}</div></div>
        <div className="flow-foot"><div><strong>A/B 流量分配</strong><small>A 版本 {traffic}% · B 版本 {100-traffic}% · 当前优胜：A（转化 +2.8%）</small></div><input type="range" min="10" max="90" value={traffic} onChange={e=>setTraffic(Number(e.target.value))}/><Button onClick={()=>updateFlowNodes(selected.id,nodes)}>保存新版本</Button></div>
      </SectionCard>
      <SectionCard title="运行健康" detail="最近 24 小时执行情况" className="flow-health"><div className="marketing-stat-strip vertical"><MiniStat label="触发人数" value="3,286"/><MiniStat label="完成流程" value="2,864"/><MiniStat label="转化率" value={`${selected.conversion}%`}/><MiniStat label="异常节点" value={String(selected.errors)}/></div>{selected.errors>0?<div className="marketing-warning"><AlertTriangle size={15}/><span>微信模板发送出现授权过期，请重新校验渠道配置。</span></div>:<div className="flow-ok"><CheckCircle2 size={18}/><strong>流程运行稳定</strong><small>所有节点均在 SLA 内执行</small></div>}</SectionCard>
    </div>
    <ConfirmDialog open={Boolean(confirm)} title="确认暂停自动化流程" detail={`暂停「${confirm?.name}」后，新用户不再进入流程；已进入用户将在当前节点停止。`} confirmLabel="确认暂停" danger onClose={()=>setConfirm(null)} onConfirm={()=>confirm&&toggleFlow(confirm.id)}/>
  </div>;
}
