import { useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, CheckCircle2, Database, Download, FileText, HardDrive, Printer, RefreshCw, Search, ShieldCheck } from "lucide-react";
import { Badge, Button, Card, Modal, Tabs } from "../../../components/ui";
import { useStudents } from "../StudentContext";
import { downloadBlob, exportStudentsCsv, nowTimestamp } from "../utils";
import { can, exportFieldsFor, reportTypesFor, type StudentReportType } from "../permissions";

const reportData=[
  {name:"4月",source:680,classCount:720,payment:382,attendance:91,loss:28,renewal:66},
  {name:"5月",source:760,classCount:790,payment:418,attendance:92,loss:26,renewal:68},
  {name:"6月",source:820,classCount:850,payment:446,attendance:90,loss:31,renewal:67},
  {name:"7月",source:910,classCount:930,payment:472,attendance:93,loss:24,renewal:71},
  {name:"8月",source:1030,classCount:1060,payment:516,attendance:94,loss:21,renewal:73},
  {name:"9月",source:1180,classCount:1210,payment:548,attendance:95,loss:19,renewal:76},
];

export function ReportsSection(){
  const {activeStudents,notify,role}=useStudents();const [period,setPeriod]=useState("月");const [report,setReport]=useState<StudentReportType>("学员来源");const [preview,setPreview]=useState(false);const [fieldsOpen,setFieldsOpen]=useState(false);const allowedFields=exportFieldsFor(role);const reportTypes=reportTypesFor(role);const effectiveReport=reportTypes.includes(report)?report:reportTypes[0];const [fields,setFields]=useState(["id","name","phone","enrolledCourse","status"] as Array<keyof typeof activeStudents[number]>);
  useEffect(()=>{if(effectiveReport!==report)setReport(effectiveReport)},[effectiveReport,report]);
  const key=effectiveReport==="学员来源"?"source":effectiveReport==="班级学员"?"classCount":effectiveReport==="缴费"?"payment":effectiveReport==="考勤"?"attendance":effectiveReport==="流失"?"loss":"renewal";
  const safeFields=fields.filter((field)=>allowedFields.includes(field));
  const exportCustom=()=>{exportStudentsCsv(activeStudents,safeFields);setFieldsOpen(false);notify("自定义字段报表已导出")};
  return <div className="student-section-body"><div className="student-section-toolbar"><div className="segmented">{["日","周","月","年"].map((item)=><button className={period===item?"active":""} onClick={()=>setPeriod(item)} key={item}>{item}</button>)}</div><span>数据更新：2026-09-15 11:30:00</span><span className="spacer"/>{can(role,"export")&&<><Button variant="secondary" onClick={()=>exportStudentsCsv(activeStudents,allowedFields)}><Download size={14}/>Excel / CSV</Button><Button variant="secondary" onClick={()=>setFieldsOpen(true)}>自定义导出</Button></>}{can(role,"print")&&<><Button variant="secondary" onClick={()=>setPreview(true)}><FileText size={14}/>PDF 预览</Button><Button onClick={()=>window.print()}><Printer size={14}/>打印</Button></>}</div>
    <Card className="student-report-layout"><aside>{reportTypes.map((item)=><button className={effectiveReport===item?"active":""} onClick={()=>setReport(item)} key={item}><span>{item}</span><small>{item==="缴费"?"单位：万元":"按当前周期"}</small></button>)}</aside><section><div className="student-card-head"><div><h2>{effectiveReport}趋势</h2><p>{period}维度 · 当前租户权限范围</p></div><Badge tone="green">数据完整</Badge></div><div className="student-report-chart"><ResponsiveContainer>{effectiveReport==="学员来源"?<PieChart><Pie data={reportData} dataKey={key} nameKey="name" innerRadius={70} outerRadius={112}>{reportData.map((item,i)=><Cell aria-label={`${item.name} ${item[key]} 人`} fill={["#2563eb","#0ea5e9","#10b981","#f59e0b","#8b5cf6","#ef4444"][i]} key={i}/>)}</Pie><Tooltip/></PieChart>:effectiveReport==="班级学员"||effectiveReport==="缴费"?<BarChart data={reportData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey={key} fill="#2563eb" radius={[5,5,0,0]}/></BarChart>:<LineChart data={reportData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Line type="monotone" dataKey={key} stroke={effectiveReport==="流失"?"#ef4444":"#10b981"} strokeWidth={3}/></LineChart>}</ResponsiveContainer></div><div className="student-report-insights"><span><strong>+12.4%</strong><small>环比变化</small></span><span><strong>98.6%</strong><small>数据完整率</small></span><span><strong>{activeStudents.length.toLocaleString("zh-CN")}</strong><small>统计样本</small></span><p>本期{effectiveReport}整体表现稳定，重点关注异常波动并结合明细下钻处理。</p></div></section></Card>
    <Modal open={preview&&can(role,"print")} onClose={()=>setPreview(false)} title="学员经营报表 PDF 预览"><div className="student-print-preview"><span>GAODUN EDUCATION OPERATIONS</span><h2>{effectiveReport}分析报告</h2><p>统计周期：2026 年 9 月 · 生成于 {nowTimestamp()}</p><div><strong>关键结论</strong><p>本期数据较上期提升 12.4%，核心班级履约稳定，需继续跟进低课时、缺勤与退费风险学员。</p></div><small>高顿业务中台 · 内部经营资料</small></div><div className="form-actions"><Button variant="secondary" onClick={()=>setPreview(false)}>关闭</Button><Button onClick={()=>window.print()}>打印 / 保存 PDF</Button></div></Modal>
    <Modal open={fieldsOpen} onClose={()=>setFieldsOpen(false)} title="自定义导出字段"><div className="student-export-fields">{([["id","学员编号"],["name","姓名"],["phone","手机号（脱敏）"],["enrolledCourse","课程"],["className","班级"],["teacher","教师"],["owner","负责人"],["status","状态"],["remainingHours","剩余课时"],["paymentState","缴费状态"],["signupTime","报名时间"]] as const).filter(([key])=>allowedFields.includes(key)).map(([key,label])=><label key={key}><input type="checkbox" checked={safeFields.includes(key)} onChange={()=>setFields((items)=>items.includes(key)?items.filter((item)=>item!==key):[...items,key])}/>{label}</label>)}</div><div className="form-actions"><Button variant="secondary" onClick={()=>setFieldsOpen(false)}>取消</Button><Button disabled={!safeFields.length} onClick={exportCustom}>导出所选字段</Button></div></Modal>
  </div>;
}

type Backup={id:string;status:"已完成"|"进行中"|"失败";size:string;creator:string;time:string;progress:number};
export function OperationsSection(){
  const {logs,role,notify,addLog}=useStudents();const [view,setView]=useState("操作日志");const [query,setQuery]=useState("");const [action,setAction]=useState("");const [page,setPage]=useState(1);const [backups,setBackups]=useState<Backup[]>([{id:"BAK-20260915-0200",status:"已完成",size:"186 MB",creator:"系统自动",time:"2026-09-15 02:00:00",progress:100},{id:"BAK-20260914-0200",status:"已完成",size:"182 MB",creator:"系统自动",time:"2026-09-14 02:00:00",progress:100},{id:"BAK-20260913-0200",status:"失败",size:"0 MB",creator:"系统自动",time:"2026-09-13 02:00:00",progress:34}]);const [restore,setRestore]=useState<Backup|null>(null);
  const visible=logs.filter((log)=>(!query||`${log.object}${log.operator}${log.detail}`.includes(query))&&(!action||log.action===action));
  const createBackup=()=>{const backup:Backup={id:`BAK-${nowTimestamp().replace(/\D/g,"")}`,status:"进行中",size:"计算中",creator:role,time:nowTimestamp(),progress:8};setBackups((items)=>[backup,...items]);notify("手动备份已开始");let progress=8;const timer=window.setInterval(()=>{progress+=23;setBackups((items)=>items.map((item)=>item.id===backup.id?{...item,progress:Math.min(progress,100),status:progress>=100?"已完成":"进行中",size:progress>=100?"191 MB":"计算中"}:item));if(progress>=100){window.clearInterval(timer);addLog("备份","学员业务数据","手动全量备份完成");notify("数据备份已完成");}},280)};
  return <div className="student-section-body"><Card className="student-workspace-card"><div className="student-card-head"><Tabs items={["操作日志","数据备份"]} active={view} onChange={setView}/>{view==="数据备份"&&<Button onClick={createBackup}><HardDrive size={14}/>创建手动备份</Button>}</div>{view==="操作日志"?<><div className="student-filter-row"><label className="student-search"><Search size={14}/><input placeholder="搜索对象、操作者或详情" value={query} onChange={(e)=>setQuery(e.target.value)}/></label><select value={action} onChange={(e)=>setAction(e.target.value)}><option value="">全部操作</option>{["创建","更新","状态变更","删除","恢复","退费","考勤","备份"].map((item)=><option key={item}>{item}</option>)}</select></div><div className="student-table-scroll"><table className="data-table"><thead><tr><th>时间</th><th>操作者</th><th>对象</th><th>操作</th><th>详情</th><th>结果</th></tr></thead><tbody>{visible.slice((page-1)*20,page*20).map((log)=><tr key={log.id}><td>{log.timestamp}</td><td>{log.operator}</td><td><strong>{log.object}</strong><small className="table-subline">{log.id}</small></td><td>{log.action}</td><td>{log.detail}</td><td><Badge tone={log.result==="成功"?"green":"red"}>{log.result}</Badge></td></tr>)}</tbody></table></div><div className="student-pagination"><span>共 {visible.length} 条</span><div><button disabled={page===1} onClick={()=>setPage(page-1)}>上一页</button><button className="active">{page}</button><button disabled={page*20>=visible.length} onClick={()=>setPage(page+1)}>下一页</button></div></div></>:<div className="student-backup-list">{backups.map((backup)=><article key={backup.id}><span className={backup.status==="已完成"?"tone-green":backup.status==="失败"?"tone-red":"tone-blue"}>{backup.status==="已完成"?<CheckCircle2 size={17}/>:backup.status==="失败"?<AlertTriangle size={17}/>:<RefreshCw size={17}/>}</span><div><strong>{backup.id}</strong><small>{backup.creator} · {backup.time} · {backup.size}</small><div className="progress"><span style={{width:`${backup.progress}%`}}/></div></div><Badge tone={backup.status==="已完成"?"green":backup.status==="失败"?"red":"blue"}>{backup.status}</Badge><Button variant="secondary" disabled={backup.status!=="已完成"} onClick={()=>setRestore(backup)}>恢复</Button></article>)}</div>}</Card><Modal open={Boolean(restore)} onClose={()=>setRestore(null)} title="恢复备份确认"><div className="student-danger-copy"><Database size={21}/><div><strong>恢复至 {restore?.time} 的数据状态？</strong><p>恢复会覆盖当前演示会话中的学员业务变更，并记录完整审计日志。</p></div></div><div className="form-actions"><Button variant="secondary" onClick={()=>setRestore(null)}>取消</Button><Button variant="danger" onClick={()=>{if(restore)addLog("恢复备份",restore.id,"恢复演练完成");setRestore(null);notify("备份恢复演练完成")}}>确认恢复</Button></div></Modal></div>;
}
